# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://rajithd.github.io"
# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)
baseurl: ""
# Google tracking id
google-tracking-id: ""
#############
# HTML Head #
#############
lang: "en"
author: "Rajith Delantha"
title: "{ Rajith Delantha }"
description:
  "Blog and website of Rajith Delantha, blogging mainly for tech. Opinions expressed are mine."
keywords: "rajith, gamage, personal, jekyll, theme"
favicon: "/img/favicon.ico"
################
# Header layout #
################
black-favicon: "/img/black-lab-glass.ico"
background-img: "../img/intro-bg.jpg"
##############################
# Dynamic Text on the Header #
##############################
dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "The best error message is the one that never shows up."
  - text: "Programming is not about typing, it's about thinking."
  - text: "Give a man a program, frustrate him for a day. Teach a man to program, frustrate him for a lifetime."
  - text: "Any fool can write code that a computer can understand. Good programmers write code that humans can understand."
#me-img: "/img/jetpacktocat.png"
# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

me-img: "https://github.com/rajithd.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"
################
# Web app mode #
################
web-app-mode: True
# Icons for Web App mode
icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"
########
# Blog #
########
post-preview-words: 96
paginate: 8
email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True
disqus-shortname: "personal-jekyll-theme"
syntax-highlight: True
############
# Timeline #
############
events:
  - image: "/img/timeline/dev_sigma.png"
    date: "August 2022 - Today"
    description: "Freelance Consultant"
  - image: "/img/timeline/xo.png"
    date: "December 2015 - August 2022"
    description: "Crossover - Software Architect"
  - image: "/img/timeline/vetstoria.jpeg"
    date: "February 2015 - December 2015"
    description: "Vetstoria - Technical Consultant"
  - image: "/img/timeline/cinglevue.jpeg"
    date: "February 2014 - January 2015"
    description: "CingleVue - Senior Software Engineer"
  - image: "/img/timeline/leapset.jpeg"
    date: "May 2013 - January 2014"
    description: "Leapset - Senior Software Engineer"
  - image: "/img/timeline/hsenid.jpeg"
    date: "November 2010 - February 2013"
    description: "hSenidMobile - Software Engineer"
# First image of the Timeline
timeline-img: "https://github.com/rajithd.png?size=500"
###########
# Contact #
###########
email: "rajithgama@gmail.com"
# Set a url pointing to your publish PGP Public Key here, and it will appear in the Contact section
pgp: False
################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb:
  "John Smith is an awesome person. He lives in Flatland, where he works on two-dimensional 
  engineering projects. In his spare time, John likes to eat cotton candy."
author_blurb_image: "/img/author.png"
##################
# Social Buttons #
##################
social:
  - icon: "github"
    url: "https://github.com/rajithd"
  - icon: "linkedin-in"
    url: "https://www.linkedin.com/in/rdelantha/"
  - icon: "rss"
    url: "https://blog.rajith.onine"
############
# 404 page #
############
err-404-img: "/img/labtocat.png"
################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page
pages_list:
  About: "about"
#  Blog: "latest-post"
  Timeline: "timeline"
  Contact: "contact"
# Exclusion list from the generated _site
exclude:
  - LICENSE
  - README.md
  - CONTRIBUTING
  - CONTRIBUTORS
  - scripts
  - Dockerfile
  - docker-compose.yml
# Pagination path
paginate_path: "blog/page:num/"
# Enable minification SASS
sass:
  style: compressed
plugins:
  - jekyll-paginate
